name: Deploy CloudFormation Template

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Zip the Lambda function
      run: zip lambda_function.zip lambda_function.py

    - name: Upload to S3 and get version ID
      id: upload_lambda
      run: |
        OUTPUT=$(aws s3api put-object --bucket ${{ vars.S3_BUCKET_NAME }} --key lambda_function.zip --body lambda_function.zip)
        VERSION_ID=$(echo $OUTPUT | jq -r '.VersionId')
        echo "Version ID: $VERSION_ID"
        echo "::set-output name=version_id::$VERSION_ID"
        
    - name: Wait for S3 version consistency
      run: sleep 10

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file deploy_hello_world.yml \
          --stack-name HelloWorldStack \
          --parameter-overrides \
            S3BucketName=${{ vars.S3_BUCKET_NAME }} \
            S3Key=${{ vars.S3_KEY }} \
            AlertEmail=${{ vars.ALERT_EMAIL }} \
            S3ObjectVersion=${{ steps.upload_lambda.outputs.version_id }} \
          --capabilities CAPABILITY_IAM
