name: Deploy CloudFormation Template

on:
  push:
    branches:
      - main
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file deploy_hello_world.yml \
          --stack-name HelloWorldStack \
          --parameter-overrides S3BucketName=$S3_BUCKET_NAME S3Key=$S3_KEY AlertEmail=$ALERT_EMAIL \
          --capabilities CAPABILITY_IAM
